apiVersion: apps/v1

kind: Deployment

metadata:

  name: app-fastapi-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: app-fastapi

  template:

    metadata:

      labels:

        app: app-fastapi

    spec:

      containers:

      - name: app-fastapi

      image: guestivalet/app-fastapi:47e67c82ea71e84e14b155bb1fb0923a6a52fd13

        ports:

        - containerPort: 80

