apiVersion: apps/v1

kind: Deployment

metadata:

  name: app-fastapi-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: app-fastapi

  template:

    metadata:

      labels:

        app: app-fastapi

    spec:

      containers:

      - name: app-fastapi

      image: guestivalet/app-fastapi:d4503cdc3c60e07e7f2b87f052e30f42edc7d02e

        ports:

        - containerPort: 80

